# Bug in python 3.x handling set comprehensions
{y for y in range(3)}
